# Generated by Django 5.1.1 on 2024-10-07 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf_app', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shelf_app.category'),
        ),
        migrations.AddField(
            model_name='book',
            name='total',
            field=models.PositiveIntegerField(default=23),
        ),
    ]
