# Generated by Django 5.1.1 on 2024-10-08 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf_app', '0003_book_category_book_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shelf_app.category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='total',
            field=models.PositiveIntegerField(),
        ),
    ]
